In [30]:
%matplotlib inline

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler

from sklearn.linear_model import LinearRegression, RANSACRegressor, LogisticRegression

from sklearn.preprocessing import PolynomialFeatures


# Linear and Logisitc Regression Demo

In [6]:
housing = pd.read_fwf("https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data", header = None)
housing

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [9]:
housing.columns = ["crime_ rate", "zoned_ land", "industry", "bounds_ river", "nox_ conc", "rooms", "age", "distance", "highways", "tax", "pt_ ratio",
"b_ estimator", "pop_ status", "price"]

In [10]:
housing.head()

crime_ rate  zoned_ land  industry  bounds_ river  nox_ conc  rooms   age  \
0      0.00632         18.0      2.31              0      0.538  6.575  65.2   
1      0.02731          0.0      7.07              0      0.469  6.421  78.9   
2      0.02729          0.0      7.07              0      0.469  7.185  61.1   
3      0.03237          0.0      2.18              0      0.458  6.998  45.8   
4      0.06905          0.0      2.18              0      0.458  7.147  54.2   

   distance  highways    tax  pt_ ratio  b_ estimator  pop_ status  price  
0    4.0900         1  296.0       15.3        396.90         4.98   24.0  
1    4.9671         2  242.0       17.8        396.90         9.14   21.6  
2    4.9671         2  242.0       17.8        392.83         4.03   34.7  
3    6.0622         3  222.0       18.7        394.63         2.94   33.4  
4    6.0622         3  222.0       18.7        396.90         5.33   36.2

In [13]:
housing.dtypes

crime_ rate      float64
zoned_ land      float64
industry         float64
bounds_ river      int64
nox_ conc        float64
rooms            float64
age              float64
distance         float64
highways           int64
tax              float64
pt_ ratio        float64
b_ estimator     float64
pop_ status      float64
price            float64
dtype: object

In [11]:
housing.describe().T

count        mean         std        min       25%         50%  \
crime_ rate    506.0    1.716290    2.653510    0.00632    0.0819    0.250895   
zoned_ land    506.0   11.363636   23.322453    0.00000    0.0000    0.000000   
industry       506.0   11.136779    6.860353    0.46000    5.1900    9.690000   
bounds_ river  506.0    0.069170    0.253994    0.00000    0.0000    0.000000   
nox_ conc      506.0    0.554695    0.115878    0.38500    0.4490    0.538000   
rooms          506.0    6.284634    0.702617    3.56100    5.8855    6.208500   
age            506.0   68.574901   28.148861    2.90000   45.0250   77.500000   
distance       506.0    3.696228    1.999689    0.58570    2.0737    3.107300   
highways       506.0    4.332016    1.417166    1.00000    4.0000    4.000000   
tax            506.0  408.237154  168.537116  187.00000  279.0000  330.000000   
pt_ ratio      506.0   18.455534    2.164946   12.60000   17.4000   19.050000   
b_ estimator   506.0  356.674032   91.294864    0.32000  375.3775  391.440000   
pop_ status    506.0   12.653063    7.141062    1.73000    6.9500   11.360000   
price          506.0   22.532806    9.197104    5.00000   17.0250   21.200000   

                      75%        max  
crime_ rate      2.326718    9.96654  
zoned_ land     12.500000  100.00000  
industry        18.100000   27.74000  
bounds_ river    0.000000    1.00000  
nox_ conc        0.624000    0.87100  
rooms            6.623500    8.78000  
age             94.075000  100.00000  
distance         5.112625    9.22290  
highways         5.000000    8.00000  
tax            666.000000  711.00000  
pt_ ratio       20.200000   22.00000  
b_ estimator   396.225000  396.90000  
pop_ status     16.955000   37.97000  
price           25.000000   50.00000

In [17]:
housing_prices = housing.price

In [18]:
housing_attributes = housing.drop("price", axis = 1)

In [19]:
housing_attributes.shape, housing_prices.shape

((506, 13), (506,))

In [23]:
scaler = MinMaxScaler()
scaler.fit(housing_attributes)

MinMaxScaler()

In [41]:
housing_attributes_scaled = scaler.transform(housing_attributes)

In [42]:
housing_attributes_scaled.max(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
MinMaxScaler().fit_transform(housing_attributes)

array([[0.        , 0.18      , 0.06781525, ..., 0.28723404, 1.        ,
        0.08967991],
       [0.00210738, 0.        , 0.24230205, ..., 0.55319149, 1.        ,
        0.2044702 ],
       [0.00210538, 0.        , 0.24230205, ..., 0.55319149, 0.98973725,
        0.06346578],
       ...,
       [0.00546574, 0.        , 0.42045455, ..., 0.89361702, 1.        ,
        0.10789183],
       [0.01036824, 0.        , 0.42045455, ..., 0.89361702, 0.99130062,
        0.13107064],
       [0.00412541, 0.        , 0.42045455, ..., 0.89361702, 1.        ,
        0.16970199]])

In [45]:
linear_regression = LinearRegression()
linear_regression.fit(housing_attributes_scaled, housing_prices)

LinearRegression()

In [46]:
linear_regression.coef_

array([  2.08448854,   1.49403979,   0.34690497,   3.00565375,
        -7.54441381,  22.43940145,   0.27658754,  -9.35981793,
         1.35281035,  -1.26826011,  -9.07603108,   3.74177288,
       -19.03479847])

In [47]:
linear_regression.intercept_

23.689291534676954

23.69: base price

In [49]:
housing_attributes_scaled[0:10]

array([[0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
        0.57750527, 0.64160659, 0.40572176, 0.        , 0.20801527,
        0.28723404, 1.        , 0.08967991],
       [0.00210738, 0.        , 0.24230205, 0.        , 0.17283951,
        0.5479977 , 0.78269825, 0.50727087, 0.14285714, 0.10496183,
        0.55319149, 1.        , 0.2044702 ],
       [0.00210538, 0.        , 0.24230205, 0.        , 0.17283951,
        0.6943859 , 0.59938208, 0.50727087, 0.14285714, 0.10496183,
        0.55319149, 0.98973725, 0.06346578],
       [0.0026154 , 0.        , 0.06304985, 0.        , 0.15020576,
        0.65855528, 0.44181256, 0.63405965, 0.28571429, 0.06679389,
        0.64893617, 0.99427606, 0.03338852],
       [0.00629805, 0.        , 0.06304985, 0.        , 0.15020576,
        0.68710481, 0.52832132, 0.63405965, 0.28571429, 0.06679389,
        0.64893617, 1.        , 0.09933775],
       [0.0023624 , 0.        , 0.06304985, 0.        , 0.15020576,
        0.54972217, 0.57466

In [51]:
linear_regression.predict(housing_attributes_scaled[:10])

array([30.10947333, 25.12810976, 31.00785588, 29.04535626, 28.48368175,
       25.44231142, 23.23025545, 20.07399474, 11.87137324, 19.61327434])

In [52]:
prices[:10].values

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [56]:
random_sample = pd.DataFrame(housing_attributes_scaled).sample(10)
random_sample

0      1         2    3         4         5         6         7   \
423  0.707223  0.000  0.646628  0.0  0.471193  0.487066  0.846550  0.166269   
291  0.007283  0.800  0.164589  0.0  0.053498  0.687296  0.255407  0.524591   
471  0.404819  0.000  0.646628  0.0  0.302469  0.511209  0.904222  0.291020   
257  0.060764  0.200  0.128666  0.0  0.539095  0.985438  0.865088  0.140705   
365  0.456772  0.000  0.646628  0.0  0.685185  0.000000  0.875386  0.118962   
302  0.008668  0.340  0.206378  0.0  0.098765  0.562177  0.159629  0.568008   
141  0.162880  0.000  0.785557  0.0  0.491770  0.279364  1.000000  0.098840   
243  0.012173  0.300  0.163856  0.0  0.088477  0.542633  0.050463  0.746747   
206  0.022426  0.000  0.371334  0.0  0.213992  0.529795  0.510814  0.436391   
68   0.012974  0.125  0.205645  0.0  0.049383  0.389538  0.349125  0.684516   

           8         9         10        11        12  
423  0.428571  0.914122  0.808511  0.005547  0.594923  
291  0.428571  0.110687  0.702128  1.000000  0.050497  
471  0.428571  0.914122  0.808511  0.996041  0.307395  
257  0.571429  0.146947  0.042553  0.981845  0.093543  
365  0.428571  0.914122  0.808511  0.893590  0.148731  
302  0.857143  0.270992  0.372340  0.966488  0.191501  
141  0.428571  0.477099  0.914894  1.000000  0.901766  
243  0.714286  0.215649  0.425532  0.944047  0.095475  
206  0.428571  0.171756  0.638298  0.994881  0.254967  
68   0.428571  0.301527  0.670213  1.000000  0.313466

In [61]:
linear_regression.predict(random_sample)

array([12.21919358, 31.98371645, 21.43104276, 43.22089462, 11.41999859,
       28.29209228,  4.4593613 , 27.29883064, 23.63354653, 17.9219948 ])

In [62]:
prices.loc[random_sample.index].values

array([13.4, 37.3, 19.6, 50. , 27.5, 26.4, 14.4, 23.7, 24.4, 17.4])

In [73]:
linear_regression.score(housing_attributes_scaled, housing_prices)

0.7198065414937174

In [65]:
ransac = RANSACRegressor()

In [66]:
ransac.fit(housing_attributes_scaled, housing_prices)

RANSACRegressor()

In [68]:
ransac.estimator_.coef_

array([ -2.90635827,  -1.68326336,   5.21082793,   1.48932255,
        -9.9761168 ,  17.26185225,  -0.94878431,  -1.65989456,
         2.8882439 ,  -2.74925953,  -3.18399527,   2.06839437,
       -10.62271279])

In [69]:
ransac.estimator_.intercept_

16.703249931839792

In [70]:
ransac.predict(random_sample)

array([10.48722381, 26.64025771, 18.30733871, 29.58662728,  7.3004063 ,
       25.31567333,  8.6291303 , 25.2672291 , 22.4570977 , 19.30417984])

In [71]:
prices.loc[random_sample.index].values

array([13.4, 37.3, 19.6, 50. , 27.5, 26.4, 14.4, 23.7, 24.4, 17.4])

In [72]:
ransac.score(housing_attributes_scaled, housing_prices)

0.4768904641438483

In [77]:
inliers = housing_attributes_scaled[ransac.inlier_mask_]
outliers = housing_attributes_scaled[~ransac.inlier_mask_]

In [78]:
ransac.score(inliers, housing_prices.loc[ransac.inlier_mask_])

0.8912663849755857

In [79]:
ransac.score(outliers, housing_prices.loc[~ransac.inlier_mask_])

0.2264417157729829

In [80]:
polynomial_features = PolynomialFeatures()

In [84]:
housing_attributes_scaled_poly = polynomial_features.fit_transform(housing_attributes_scaled)

In [85]:
housing_attributes_scaled_poly.shape

(506, 105)

In [87]:
quadratic_regression = LinearRegression()
quadratic_regression.fit(housing_attributes_scaled_poly, housing_prices)

LinearRegression()

In [89]:
quadratic_regression.score(housing_attributes_scaled_poly, housing_prices)

0.8527008230672175

In [93]:
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None)
iris.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]

In [94]:
iris

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [103]:
iris_attributes = iris.drop("class", axis = 1)
iris_classes = iris["class"]

In [104]:
iris_attributes_scaled = MinMaxScaler().fit_transform(iris_attributes)
iris_attributes_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [105]:
logistic_regression = LogisticRegression(C = 1e9)

In [106]:
logistic_regression.fit(iris_attributes_scaled, iris_classes)

LogisticRegression(C=1000000000.0)

In [107]:
logistic_regression.coef_

array([[-18.29679129,  29.19813694, -37.89417388, -38.3219437 ],
       [ 13.58611302,  -6.58018128,  -8.87560643,  -2.78717031],
       [  4.71067827, -22.61795566,  46.76978031,  41.10911401]])

In [109]:
logistic_regression.intercept_

array([ 25.9014194 ,  14.7266206 , -40.62803999])

In [110]:
logistic_regression.score(iris_attributes_scaled, iris_classes)

0.9866666666666667

In [111]:
PolynomialFeatures(degree = 7).fit_transform(iris_attributes_scaled)

array([[1.00000000e+00, 2.22222222e-01, 6.25000000e-01, ...,
        5.77244430e-10, 3.54764806e-10, 2.18032537e-10],
       [1.00000000e+00, 1.66666667e-01, 4.16666667e-01, ...,
        5.77244430e-10, 3.54764806e-10, 2.18032537e-10],
       [1.00000000e+00, 1.11111111e-01, 5.00000000e-01, ...,
        3.24699992e-10, 2.66073604e-10, 2.18032537e-10],
       ...,
       [1.00000000e+00, 6.11111111e-01, 4.16666667e-01, ...,
        1.57581908e-01, 1.75247340e-01, 1.94893123e-01],
       [1.00000000e+00, 5.27777778e-01, 5.83333333e-01, ...,
        3.59963549e-01, 4.42455196e-01, 5.43851178e-01],
       [1.00000000e+00, 4.44444444e-01, 4.16666667e-01, ...,
        8.61097024e-02, 8.77723898e-02, 8.94671819e-02]])

## Quiz

In [123]:
red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep = ";")
red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [145]:
red_quality = red.quality

In [146]:
red_attributes = red.drop("quality", axis = 1)

In [147]:
scaler = MinMaxScaler()
scaler.fit(red_attributes)

MinMaxScaler()

In [140]:
MinMaxScaler().fit_transform(red_attributes)

array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
        0.15384615],
       [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
        0.21538462],
       [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
        0.4       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
        0.27692308],
       [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
        0.4       ]])

In [148]:
red_attributes_scaled = scaler.transform(red_attributes)

In [149]:
linear_regression = LinearRegression()
linear_regression.fit(red_attributes_scaled, red_quality)

LinearRegression()

In [150]:
linear_regression.coef_

array([ 0.28239325, -1.58204178, -0.18256395,  0.23843654, -1.12266087,
        0.30965466, -0.92387606, -0.24354145, -0.52533949,  1.53027847,
        1.79528504])

In [151]:
linear_regression.intercept_

5.712552996670392

In [152]:
linear_regression.score(red_attributes_scaled, red_quality)

0.36055170303868833

In [153]:
polynomial_features = PolynomialFeatures()

In [154]:
red_attributes_scaled_poly = polynomial_features.fit_transform(red_attributes_scaled)

In [155]:
red_attributes_scaled_poly.shape

(1599, 78)

In [156]:
quadratic_regression = LinearRegression()
quadratic_regression.fit(red_attributes_scaled_poly, red_quality)

LinearRegression()

In [157]:
quadratic_regression.score(red_attributes_scaled_poly, red_quality)

0.4346357868782813

In [158]:
PolynomialFeatures(degree = 2).fit_transform(red_attributes_scaled)

array([[1.        , 0.24778761, 0.39726027, ..., 0.01896805, 0.02118839,
        0.02366864],
       [1.        , 0.28318584, 0.52054795, ..., 0.04392413, 0.04514049,
        0.04639053],
       [1.        , 0.28318584, 0.43835616, ..., 0.03671699, 0.0412713 ,
        0.04639053],
       ...,
       [1.        , 0.15044248, 0.26712329, ..., 0.06325074, 0.1005988 ,
        0.16      ],
       [1.        , 0.11504425, 0.35958904, ..., 0.05177669, 0.06301244,
        0.07668639],
       [1.        , 0.12389381, 0.13013699, ..., 0.03904765, 0.07904192,
        0.16      ]])